sudo: false

# version automatically picked up from .ruby-version
language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler jekyll
  - npm install

before_script:
  - npm run setup
  - chmod +x ./bin/setup
  - ./bin/setup
  - bundle exec jekyll build

script: bundle exec ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml,/facebook.com/"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - LC_ALL=en_US.UTF-8
    - JEKYLL_ENV=production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: deployment
