# Mandatory settings

blog_theme: light # Or use dark
name: <RB/>
paginate: 25
url: http://robynbursnell.com


# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
#ga_analytics: UA-28631876-6 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false # Change to false if not
scrollappear_enabled: false # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: true # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  github: nielsenramon # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  email: # Add your Email address
  tumblr: # Add your Tumblr handle
  instagram: # Add your Instagram handle
  steam: # Add your Steam handle


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
